### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by Fr-Dae** [heinwessels/factorio-configurable-valves#1]
hello,i try to update this mod https://mods.factorio.com/mod/Flow_Control_Fix
could i use your sources code and mentionned you?

if yes, any idea how to do that ?

**Comment by heinwessels** [comment]
Hello! It might be easier to simply depend on this mod, and use the valve I provide. 2.0 valves are a little tricky to implement and debug issues, and work different than 1.1 valves.

I'm gonna try do the same for the Flow Control mod.

If you want to handle migrating valves from 1.1 you can see how I did it for Pyanodons in the `migrations/` folder.

**Comment by Fr-Dae** [comment]
thanks you for your information, it's out of my skill atm :/
